using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public static class StaticInfo 
{
    public static string Money = "Money";
    public static string Diamon = "Diamon";
    public static string Energy = "Energy";

    public static string AlchimyOpen = "AlchimyOpen";

    public static string PlateIndex = "Plate";
    public static string BankIndex = "Bank";
    public static string BackGroundIndex = "BackGround";

    public static string[] name = new string[] { "Hellstaff ","𝓜𝓞𝓢𝓒𝓞𝓦 ","ᴜɴɪᴄᴏʀɴ ",    "Mr_KiLLaURa ","Dominator ",   "black coffe ","Ť.ħ.ê_Ĉ.õ.о.Ł ","Darkshaper",   "GAMER",
    "რฉςh","Skillet","FEISKO","u n i v e r s e","AnnyMars","Bloodray", "Blackseeker","Delan","Alien",
"Simple",
"Kerry",    "Bloodfire",
"Dark_Sun",
"Aria",
"Anen",
"Crazy",
"Lightseeker",

"Mr_Mix",
"WOGY",
"Quemal",

"Ironfire",
"Kirizan",  "Loni",
"Kezan",
"iSlate",   "Jay",
"Miromice", "GawelleN",
"Juce", "Nuliax",
    "Topmen",
"Kitax",    "Moda",
"Alsantriu",    "Error parent",
"Quashan",  "Azag",
"Blackbran",    "Runeman",
"Blis", "DrayLOV",
"Envia",    "Gralind",
"Kakashkaliandii",  "Kizshur",
"Dilkre",   "Kiso",
"Rageseeke",    "Afina",
"Eriena",  
"Hellblad",
"kro",  "Manesenc",
"OTAN", "Zack",
"Dark Devi",    "Dr.Wha",
"Elastic Skun", "Enditalin",
"Erenng",   "EXIBUZY",
"Eyalane",  "Gaiauac",
"Gathri",   "Gaviru",
"Hellmaste",    "Kamic",
"Knights from Berni",   "Kulalbin",
"Kulasiu",
    "Malodor",
    "Manri",


    "Stee",
    "Chupa chup",
    "Daiktila",
    "DarkDevI",

    "do no",
"Do not li",    "Dordre",
"Dozilkre", "Eng.Me",
"Erica",    "Gamb",
"Gol",  "HELL",
"Khiceo",   "Kikor",
"Kiriziu",  "Kiutondy",
"Koneta",   "Kosmeno",
"Kuv",  "nadnes",
"Ovele",    "Redfur",
"SkyHor",   "someon",
    "Tempu",
"your proble", 
"Granigr",  "HelloTh",
"Ideal s",  "IWant",
    "kids_seas",
"Kru Sal",
   "Sofi P",
"Some", "Someth",
    "Xisy",
"you terori",   "Your wo",
"anonym",   "Bludw",
"Brad", "ChallengeM",
"Dela", "Duki",
  "Elizab",
  "Funny d",
  
"Gavik",    "Glda",
    "Gol",
    "Gug",
"Hydrogen", "Hyst",
"Iphonedivor",  "kin",
"Kip",  "Kirim",
"Kula", "luis",
    "Not Gonna ",
"Qusi", "Ucan",
   
"Arabella", 
"Best W",   "Bey",

"Braj", "Bras",
"BroW", "Buri",

"Dai",  "Ddda",
    "Dete",
"Dianag",   "DilcuePr",
"Dobp",
"Duzsh",    "Endie",
"Ert",  "FireWa",
"Gand", 
"Gasha",    "Gaudi",
"Gavi", "Gavinran",
"GAZA",
    "Glo",
    "Goldenf",
"Goldf",    "Grani",
"Gtony",    "Kam",
"Kefran",   "Ke",
"Keler",    "Kr",
   "lol",
"Mar",  "mIni-L",
   
"Nah", 
"Quin", "Qulce",
  "Qumen",
"Reem",

"Xmatarr",  "Xtr",

    "Agagam",
    "Anaya",
"Ara",  "Beazez",
"Binth",    "Bloodham",
"Bola",
"Cashoutmas",   "Der ",
   "Dianalme",
"Dianantr", "Disha",
"Dokti",    "Doombl",
"Dor",  "Doril",
"Dukti",
"Farar",
"Fordrella",    "Gaeu",
    "Gavinr",
"Gavir",    "Gavi",
"Getaia",   "Gholbir",
"Gholbith", "Ghord",
"Gia",  "Gieta",
"Gigaf",    "Gin",
"Graniju",  "great",
"griby taet ",  "Gri",
"Groti",    
"Hallo",    "Keler",
"Kula",
"melody of ",

"Qua",  "Qudani",
"Quend",    "Qupha",
"Qutt", "Sir",
"Xarcon",  
"Xelle",    "Ximi",
"Xine", 
"Bra", 
"Burk", "Byne",  "Dondal",
};
}
